# Generated by Django 6.0.1 on 2026-01-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartas',
            new_name='Carta',
        ),
        migrations.RenameModel(
            old_name='Notas',
            new_name='Nota',
        ),
    ]
