# Generated by Django 6.0.1 on 2026-01-27 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0002_rename_cartas_carta_rename_notas_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='creada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
