# Generated by Django 6.0.1 on 2026-02-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0003_nota_creada'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='correo_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
