# Generated by Django 6.0.1 on 2026-03-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0004_carta_correo_enviado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
