# Generated by Django 6.0.1 on 2026-03-24 04:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0005_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='fecha',
            new_name='creada',
        ),
        migrations.AlterField(
            model_name='foto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
