# Generated by Django 6.0.1 on 2026-04-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0006_rename_fecha_foto_creada_alter_foto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='autor',
            field=models.CharField(default='Efra ❤️', max_length=20),
        ),
    ]
