# Generated by Django 6.0.1 on 2026-04-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0007_nota_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
