# Generated by Django 6.0.1 on 2026-04-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0008_alter_carta_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='subida_por',
            field=models.CharField(choices=[('admin', 'Efra (Admin)'), ('ella', 'Abi ❤️')], default='admin', max_length=20),
        ),
    ]
